# Generated by Django 5.1.7 on 2025-04-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator'), ('client', 'Client')], default='client', max_length=20),
        ),
    ]
