# Generated by Django 5.2 on 2025-05-29 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_admin', '0003_alter_user_address_alter_user_name_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
