# Generated by Django 5.2 on 2025-05-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_admin', '0004_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
