# Generated by Django 5.2 on 2025-06-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_order_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='direccion_envio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
