# Generated by Django 5.2 on 2025-08-19 21:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pay',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='pay',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('fallido', 'Fallido')], default='pendiente', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='pay',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'pendiente')), fields=('pedido',), name='uniq_pedido_pago_pendiente'),
        ),
    ]
