# Generated by Django 5.2 on 2025-08-19 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_pay_actualizado_pay_creado_alter_pay_estado_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pay',
            name='uniq_pedido_pago_pendiente',
        ),
    ]
