# Generated by Django 5.2 on 2025-08-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_remove_pay_uniq_pedido_pago_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='comprobante_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pay',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='pay',
            name='external_redirect_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pay',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
