# Generated by Django 5.2 on 2026-01-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_order_apellido_invitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='codigo_descuento_usado',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='dni_invitado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
