# Generated by Django 5.2 on 2025-08-22 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_pay_comprobante_url_pay_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='comprobante_archivo',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
    ]
