# Generated by Django 5.2 on 2025-08-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_pay_comprobante_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('completado', 'Completado'), ('fallido', 'Fallido')], default='pendiente', max_length=20),
        ),
    ]
